import { invoke } from "@tauri-apps/api/core";
import type { DeletePreview, FileDocument, Point, ProjectFile, ProjectSnapshot, RecoveryEntry } from "../domain/project";
import type { WorkflowEdge } from "../domain/graph";
import type { UiMode } from "../domain/uiMode";
import type { ImportSummary } from "../components/ImportReview";
import type { TemplateProposal } from "../templates/workflows";
import type { Skill, SkillAssignment } from "../domain/skills";
import type { RunEvent, RunSummary } from "../domain/runs";

export const createProject = (parentPath: string, name: string) => invoke<ProjectSnapshot>("create_project", { parentPath, name });
export const openProject = (path: string) => invoke<ProjectSnapshot>("open_project", { path });
export const createAgent = (projectRoot: string, name: string, purpose: string) => invoke<ProjectSnapshot>("create_agent", { projectRoot, name, purpose });
export const createAgentWithContent = (projectRoot: string, name: string, purpose: string, content: string) => invoke<ProjectSnapshot>("create_agent_with_content", { projectRoot, name, purpose, content });
export const renameAgent = (projectRoot: string, agentId: string, newName: string) => invoke<ProjectSnapshot>("rename_agent", { projectRoot, agentId, newName });
export const previewDeleteAgent = (projectRoot: string, agentId: string) => invoke<DeletePreview>("preview_delete_agent", { projectRoot, agentId });
export const trashAgent = (projectRoot: string, agentId: string) => invoke<RecoveryEntry>("trash_agent", { projectRoot, agentId });
export const listRecoveryEntries = (projectRoot: string) => invoke<RecoveryEntry[]>("list_recovery_entries", { projectRoot });
export const restoreRecoveryEntry = (projectRoot: string, actionId: string) => invoke<ProjectSnapshot>("restore_recovery_entry", { projectRoot, actionId });
export const saveAgentPosition = (projectRoot: string, agentId: string, position: Point) => invoke<void>("save_agent_position", { projectRoot, agentId, x: position.x, y: position.y });
export const listProjectFiles = (projectRoot: string) => invoke<ProjectFile[]>("list_project_files", { projectRoot });
export const readProjectDocument = (projectRoot: string, relativePath: string) => invoke<FileDocument>("read_project_document", { projectRoot, relativePath });
export const writeProjectDocument = (projectRoot: string, relativePath: string, content: string, expectedRevision: string) => invoke<FileDocument>("write_project_document", { projectRoot, relativePath, content, expectedRevision });
export const createProjectFile = (projectRoot: string, parentPath: string, name: string, initialContent: string) => invoke<FileDocument>("create_project_file", { projectRoot, parentPath, name, initialContent });
export const revealInFinder = (projectRoot: string, relativePath?: string) => invoke<void>("reveal_in_finder", { projectRoot, relativePath: relativePath ?? null });
export const getUiMode = (projectRoot: string) => invoke<UiMode>("get_ui_mode", { projectRoot });
export const setUiMode = (projectRoot: string, mode: UiMode) => invoke<UiMode>("set_ui_mode", { projectRoot, mode });
export const inspectProject = (path: string) => invoke<ImportSummary>("inspect_project", { path });
export const applyTemplate = (projectRoot: string, proposal: TemplateProposal) => invoke<ProjectSnapshot>("apply_template", { projectRoot, ...proposal });
export const upsertEdge = (projectRoot: string, edge: WorkflowEdge) => invoke<ProjectSnapshot>("upsert_edge", { projectRoot, edge });
export const deleteEdge = (projectRoot: string, edgeId: string) => invoke<ProjectSnapshot>("delete_edge", { projectRoot, edgeId });
export const listSkills = (projectRoot: string) => invoke<Skill[]>("list_skills", { projectRoot });
export const listSkillAssignments = (projectRoot: string) => invoke<SkillAssignment[]>("list_skill_assignments", { projectRoot });
export const setSkillAssignment = (projectRoot: string, agentId: string, skillId: string, assigned: boolean) => invoke<SkillAssignment[]>("set_skill_assignment", { projectRoot, agentId, skillId, assigned });
export type SkillImportPreview = { skillName: string; destination: string; files: Array<{ path: string; size: number; executableLooking: boolean }>; collisions: string[]; hasExecutableLookingFiles: boolean };
export const inspectSkillImport = (sourcePath: string, projectRoot: string) => invoke<SkillImportPreview>("inspect_skill_import", { sourcePath, projectRoot });
export const applySkillImport = (sourcePath: string, projectRoot: string) => invoke<Skill[]>("apply_skill_import", { sourcePath, projectRoot });
export const listRuns = (projectRoot: string) => invoke<RunSummary[]>("list_runs", { projectRoot });
export const startRun = (projectRoot: string, agentId: string, task: string) => invoke<RunSummary>("start_run", { projectRoot, agentId, task });
export const decideRun = (projectRoot: string, runId: string, approved: boolean) => invoke<RunSummary>("decide_run", { projectRoot, runId, approved });
export const cancelRun = (projectRoot: string, runId: string) => invoke<RunSummary>("cancel_run", { projectRoot, runId });
export const resumeRun = (projectRoot: string, runId: string) => invoke<RunSummary>("resume_run", { projectRoot, runId });
export const listRunEvents = (projectRoot: string, runId: string) => invoke<RunEvent[]>("list_run_events", { projectRoot, runId });
